import CardsToolDocuments from "@/components/containers/cards-tool-documents";
import WrapperContent from "@/components/containers/wrapper-content";
import Separator from "@/components/ui/separator";
import React from "react";
import { Metadata } from "next";
import { documentsRepository } from "@/repository/documents";
import Title from "@/components/ui/title";
import roads from "@/utils/data/road.json";

export const metadata: Metadata = {
  title: "Documentos FitJaguarGo",
  description: "Generated by create next app",
};

async function getData() {
  const data = await documentsRepository.getDocuments();
  return data;
}

const ToolsDocumentsPage = async () => {
  const data = await getData();

  return (
    <main>
      <Separator height="120px" />
      <WrapperContent>
        <Title>Documentos</Title>
        <CardsToolDocuments documents={data} roads={roads} />
      </WrapperContent>
    </main>
  );
};

export default ToolsDocumentsPage;
